---
title: "R Notebook"
output: html_notebook
---
To do's:
- recode this location: 高田, incorrectly mapped to China

```{r}
library(ggmap)
library(lubridate)

# load in saved data

loc_names <- read_csv('../../data/geocoded_locations.csv')
load('jpmapimage')
df <- read_csv('../../data/bloom.csv')
# df to convert codes to locations
high_var_rows <- loc_names %>% left_join(df,c('loc_names'='l_name')) %>% select(loc_names,lon,lat,l_code)
names(high_var_rows)
```


```{r}

jp %>% ggmap() + 
  geom_point(data = high_var_rows,
             aes(x=lon,y=lat),
             size = 1)# + geom_text(data=high_var_rows,aes(x=lon,y=lat,label=loc_names),size=2)

# TO DO: 
# look at different ways to get map from google, e.g. geospatial, 

```

```{r}
ggplot(lastyr) + geom_point(aes(x=lat,y=lon,color=l_code)) + labs(title="My Title",subtitle = 'My subtitle') + theme(
        # title element styling
        plot.title = element_text(size = 20, margin = margin(b = -16)),
        plot.subtitle = element_text(size = 16, color = "grey30", margin = margin(b = 2),hjust=1),
        legend.direction = "vertical",
        legend.title = element_text(size = 18,colour = "grey30"),
        legend.text = element_text(size = 12,colour = "grey30"),
        legend.position = c(.8,.2),
        legend.key.height = unit(1,'cm'),
        legend.box=margin(rep(100,4)),
        legend.key = element_rect(fill = NA),
        legend.background = element_rect(color='pink') 
  ) + guides(colour = guide_legend(title.position = "top",override.aes = list(size=8)))

```
